### ISSUE TITLE
error when `python setup.py install`

### ISSUE THREAD

**Issue by zhangxiann** [norse/aestream#7]
```
running install
running bdist_egg
running egg_info
creating aedat.egg-info
writing aedat.egg-info\PKG-INFO
writing dependency_links to aedat.egg-info\dependency_links.txt
writing top-level names to aedat.egg-info\top_level.txt
writing manifest file 'aedat.egg-info\SOURCES.txt'
reading manifest file 'aedat.egg-info\SOURCES.txt'
writing manifest file 'aedat.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py:287: UserWarning: Error checking compiler version for cl: [WinError 2] 系统找不到指定的
文件。
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
building 'aedat' extension
creating D:\Project\aedat-master\build
creating D:\Project\aedat-master\build\temp.win-amd64-3.8
creating D:\Project\aedat-master\build\temp.win-amd64-3.8\Release
Emitting ninja build file D:\Project\aedat-master\build\temp.win-amd64-3.8\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/1] cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IE:\SoftWare\Anaconda3\lib\site-pa
ckages\torch\include -IE:\SoftWare\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IE:\SoftWare\Anaconda3\lib\site-packages\torch\include\T
H -IE:\SoftWare\Anaconda3\lib\site-packages\torch\include\THC -IE:\SoftWare\Anaconda3\include -IE:\SoftWare\Anaconda3\include "-IC:\Program Files (x86)\Micro
soft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\s
hared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c D:\Project\aedat-master\convert.cp
p /FoD:\Project\aedat-master\build\temp.win-amd64-3.8\Release\convert.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=aedat -D_GLIBCXX_USE_CXX11_A
BI=0 /std:c++14
FAILED: D:/Project/aedat-master/build/temp.win-amd64-3.8/Release/convert.obj
cl /showIncludes /nologo /Ox /W3 /GL /DNDEBUG /MD /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -IE:\SoftWare\Anaconda3\lib\site-packages
\torch\include -IE:\SoftWare\Anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IE:\SoftWare\Anaconda3\lib\site-packages\torch\include\TH -IE:
\SoftWare\Anaconda3\lib\site-packages\torch\include\THC -IE:\SoftWare\Anaconda3\include -IE:\SoftWare\Anaconda3\include "-IC:\Program Files (x86)\Microsoft V
isual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared"
 "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" -c D:\Project\aedat-master\convert.cpp /FoD
:\Project\aedat-master\build\temp.win-amd64-3.8\Release\convert.obj -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=aedat -D_GLIBCXX_USE_CXX11_ABI=0 /
std:c++14
d:\project\aedat-master\aedat.hpp(24): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(24): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(24): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(30): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(30): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(30): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(30): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(38): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(38): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(38): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(38): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(72): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(72): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(72): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(72): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(88): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(88): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(88): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(88): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(104): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(104): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(104): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(104): error C2059: syntax error: ')'
d:\project\aedat-master\aedat.hpp(120): error C2059: syntax error: '('
d:\project\aedat-master\aedat.hpp(120): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
d:\project\aedat-master\aedat.hpp(120): error C2535: 'int AEDAT::__attribute__(void)': member function already defined or declared
d:\project\aedat-master\aedat.hpp(24): note: see declaration of 'AEDAT::__attribute__'
d:\project\aedat-master\aedat.hpp(120): error C2059: syntax error: ')'
d:\project\aedat-master\aedat4.hpp(10): fatal error C1083: Cannot open include file: 'sys/mman.h': No such file or directory
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1533, in _run_ninja_build
    subprocess.run(
  File "E:\SoftWare\Anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    setup(
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "E:\SoftWare\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\SoftWare\Anaconda3\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\SoftWare\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\install.py", line 67, in run
    self.do_egg_install()
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "E:\SoftWare\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\SoftWare\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 167, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\bdist_egg.py", line 153, in call_command
    self.run_command(cmdname)
  File "E:\SoftWare\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\SoftWare\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "E:\SoftWare\Anaconda3\lib\distutils\command\install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "E:\SoftWare\Anaconda3\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "E:\SoftWare\Anaconda3\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "E:\SoftWare\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "E:\SoftWare\Anaconda3\lib\distutils\command\build_ext.py", line 340, in run
    self.build_extensions()
  File "E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 670, in build_extensions
    build_ext.build_extensions(self)
  File "E:\SoftWare\Anaconda3\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "E:\SoftWare\Anaconda3\lib\distutils\command\build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "E:\SoftWare\Anaconda3\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "E:\SoftWare\Anaconda3\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "E:\SoftWare\Anaconda3\lib\distutils\command\build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 643, in win_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1250, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "E:\SoftWare\Anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1555, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

```

**Comment by cpehle** [comment]
Thank you for pointing out this issue, to support windows I would need to eliminate the use of mmap among other things.

**Comment by Jegp** [comment]
Closing this issue since we have new python build routines.
